### ISSUE TITLE
NEED TO ADD /etc/fstab

### ISSUE THREAD

**Issue by IchiroKano** [IBM-Bluemix-Docs/BlockStorage#1]
Hello

After set up the Block Storage mounting, /etc/fstab need to be edited. Otherwise, Block Storage will be disappeared  when the Server is rebooted.

(T.T) We had problem at production system no storage mounted.

**Comment by vickmuir** [comment]
Thank you for your feedback. We are looking into it.

**Comment by vickmuir** [comment]
An updated version of accessing_block_storage_linux.md has been posted.
