### ISSUE TITLE
Block Storage "Disaster Recovery - Failover from accessible Primary Volume" topic "Replica" option no longer in UI or Actions Drop-down.

### ISSUE THREAD

**Issue by enebab** [IBM-Bluemix-Docs/BlockStorage#10]
Block Storage "Disaster Recovery - Fail over from an accessible Primary volume" online docs and procedures referenced below points customers to choose "**Replica**" action but this action no longer exists in the UI.

https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-dr-accessible
- Step 3 in the "Authorizing the host in the UI" to click on "Replica".   There is no "Replica" in the menus to choose from.

https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-dr-accessible#failovertoreplica
- Step 2 in the "Fail over to replica in the UI" to click on "Replica".   There is no "Replica" in the menus to choose from.

If the purpose is to authorize a host first, then just choose "**Authorize Host**" from the Action menu.

![REPLICA-menu-missing](https://user-images.githubusercontent.com/34173685/116085281-4769f980-a664-11eb-820f-0b34dffd38db.png)

**Comment by vickmuir** [comment]
Confirmed the UI change, updated the docs.
