### ISSUE TITLE
Compliance language out of date

### ISSUE THREAD

**Issue by mraquinn** [IBM-Bluemix-Docs/BlockStorage#11]
This language is out of date.  "EU Data Protection Directive 95/46/EC compliance" is no longer a valid statement since the introduction of GDPR.

Storage is validated for Federal Information Processing Standard (FIPS) Publication 140-2, Federal Information Security Management Act (FISMA), Health Insurance Portability and Accountability Act (HIPAA). Storage is also validated for Payment Card Industry (PCI), Basel II, California Security Breach Information Act (SB 1386), and EU Data Protection Directive 95/46/EC compliance.

**Comment by vickmuir** [comment]
Thank you for your feedback. I have forwarded it to our Compliance Focal and Product Manager, and we will update the statement shortly.
