### ISSUE TITLE
Windows Server 2019 Not Prompting for Restart

### ISSUE THREAD

**Issue by thowden** [IBM-Bluemix-Docs/BlockStorage#12]
Hi

https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-mountingWindows#adding-iscsi-support-for-mpio-devices

Step 4. When you're prompted to restart the computer, click Yes.

Except in Windows Server 2019, there is no prompt for a restart. 

Is a manual restart required, or is a service restart sufficient ?

**Comment by vickmuir** [comment]
Reviewed the comment. As stated in the Document, the steps were based on Windows Server 2012, not the Window Server 2019. It appears that the newest version of Windows Server OS does not prompt to reboot at this point and it's safe to continue without restarting the server. The wording of Step 4 is going to be updated shortly.
