### ISSUE TITLE
where is portable storage doc in port Block storage doc page ? 

### ISSUE THREAD

**Issue by threen134** [IBM-Bluemix-Docs/BlockStorage#13]
does portable storage belong to Block storage class ? 
I can not find it in your block storage section of cloud doc,  I have to search it in your whole of doc , and finally find it in virtual server doc .
can you optimize your doc section ? 
https://cloud.ibm.com/docs/BlockStorage
![Xnip2022-11-29_10-45-38](https://user-images.githubusercontent.com/13844762/204426718-4f5c9101-4e72-47da-b554-54016b688c10.jpg)

**Comment by vickmuir** [comment]
Thank you for the feedback. Portable storage is not part of the Block Storage offering, even though the PSVs are displayed in the same location in the UI for historical reasons. 
I've added a link to our [Block Storage FAQs](https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-block-storage-faqs#portablestorageredirect) to direct readers to the correct location and contacted our UI team to ensure customers can have a link to the right documentation repository when they view Block Storage and Portable Storage in the future.
