### ISSUE TITLE
Edit for: " Add iSCSI support for MPIO" 

### ISSUE THREAD

**Issue by mester-ibm** [IBM-Bluemix-Docs/BlockStorage#2]
For Windows 2008 servers, customers will only be able to enable the " Add support for iSCSI devices " checkbox, after a connection to the target is made. So we are requesting an edit to the section to include the below excerpt from Microsoft help docs:

 Note  ( applies to Windows Server 2008)
 Adding support for iSCSI allows the Microsoft Device Specific Module (MSDSM) to claim all iSCSI devices for MPIO, which first requires a connection to an iSCSI Target.

**Comment by vickmuir** [comment]
Thank you for your feedback. It has been reviewed and the note is going to be part of the instructions.
