### ISSUE TITLE
some mistake in mask xxxlp1 in the documentation

### ISSUE THREAD

**Issue by notras** [IBM-Bluemix-Docs/BlockStorage#4]
Hi in my particular case when I tried to format block storage, disk name have been ended to xxxp1 and not xxx1p1 like provided in documentation.
[root@master1 ~]#  fdisk -l | grep /dev/mapper/
3600a0980383056526e2b4f4e6d387a683600a0980383056526e2b4f4e6d387a68p1
That confusing because in that case grep command will not show that block device which is happen in that particular case, and additional time need to figure it out. 
Please change mask example to xxxp1 from xxx1p1 in the documentation.

**Comment by vickmuir** [comment]
Thank you for the feedback. The change has been made. It will take a few minutes for the documentation to update in all languages.
