### ISSUE TITLE
Extra word in sentence

### ISSUE THREAD

**Issue by cpschult** [IBM-Bluemix-Docs/BlockStorage#8]
The following sentence in section Provisioning considerations has an extra word.
>Conversely, if the block size that is used by your application is larger than 16 KB, the throughput limit is realized before *to* the IOPS limit.

Possibly it should read:
>Conversely, if the block size that is used by your application is larger than 16 KB, the throughput limit is realized before the IOPS limit.

**Comment by vickmuir** [comment]
Thank you for catching that. The docs have been updated on the backend and the change will be visible to the public in a short while.
